#WARNING: as this file contains credentials, be sure to set correct file permissions
{%- set services = salt['pillar.get']('profile:matrix:matterbridge:servers') %}
{%- for service, servers in services.items() %}
[{{service}}]
    {%- for server, options in servers.items() %}
    [{{service}}.{{server}}]
    {%- for key, value in options.items() %}
    {{key}}={{value}}
    {%- endfor %}

    {%- endfor %}
{%- endfor %}

{%- set gateways = salt['pillar.get']('profile:matrix:matterbridge:gateways') %}
{%- for gateway, accounts in gateways.items() %}
[[gateway]]
name="{{gateway}}"
enable=true
inout = [
    {%- for account, channel in servers.items() %}
    { account="{{account}}", channel="{{channel}}" },
    {%- endfor %}
]
{%- endfor %}
