stages:
  - validate
  - test
  - deploy

validate:
  stage: validate
  before_script:
    - bin/prepare_test_env.sh -i opensuse
  script: bin/test_validate.sh
  tags:
    - docker

validate_show_highstate_leap_15.0:
  stage: validate
  before_script:
    - bin/prepare_test_env.sh -i opensuse -g
    - bin/get_formulas.py -c -d /srv/formula -s --clone-from 'https://gitlab.infra.opensuse.org/saltstack-formulas' --clone-branch production
  script: bin/test_show_highstate.sh
  tags:
    - docker

validate_show_highstate_leap_42.3:
  stage: validate
  before_script:
    - bin/prepare_test_env.sh -i opensuse -g -o Leap,42,3
    - bin/get_formulas.py -c -d /srv/formula -s --clone-from 'https://gitlab.infra.opensuse.org/saltstack-formulas' --clone-branch production
  script: bin/test_show_highstate.sh
  tags:
    - docker

validate_show_highstate_sle15:
  stage: validate
  before_script:
    - bin/prepare_test_env.sh -i opensuse -g -o SLES,15,0
    - bin/get_formulas.py -c -d /srv/formula -s --clone-from 'https://gitlab.infra.opensuse.org/saltstack-formulas' --clone-branch production
  script: bin/test_show_highstate.sh
  tags:
    - docker

validate_show_highstate_sle12sp3:
  stage: validate
  before_script:
    - bin/prepare_test_env.sh -i opensuse -g -o SLES,12,3
    - bin/get_formulas.py -c -d /srv/formula -s --clone-from 'https://gitlab.infra.opensuse.org/saltstack-formulas' --clone-branch production
  script: bin/test_show_highstate.sh
  tags:
    - docker

validate_show_highstate_sle11sp4:
  stage: validate
  before_script:
    - bin/prepare_test_env.sh -i opensuse -g -o SLES,11,4
    - bin/get_formulas.py -c -d /srv/formula -s --clone-from 'https://gitlab.infra.opensuse.org/saltstack-formulas' --clone-branch production
  script: bin/test_show_highstate.sh
  tags:
    - docker

validate_show_highstate_latest_leap_upstream_formulas:
  stage: validate
  before_script:
    - bin/prepare_test_env.sh -i opensuse -g
    - bin/get_formulas.py -c -d /srv/formula -s
  script: bin/test_show_highstate.sh
  allow_failure: true
  except:
    - production@infra/salt
  tags:
    - docker

test_nginx:
  stage: test
  before_script:
    - bin/prepare_test_env.sh -i opensuse -g -p nginx
    - bin/get_formulas.py -c -d /srv/formula -s --clone-from 'https://gitlab.infra.opensuse.org/saltstack-formulas' --clone-branch production -f nginx
  script: bin/test_nginx.sh
  tags:
    - docker

deploy_job:
  stage: deploy
  script: sudo salt-call event.fire_master $CI_DEPLOY_PASSWORD salt/fileserver/gitfs/update
  only:
    - production@infra/salt
  tags:
    - shell
