stages:
  - test
  - deploy

test_roles:
  stage: test
  before_script:
    - zypper -qn in --no-recommends python3 python3-PyYAML
  script: bin/test_roles.py
  tags:
    - docker

test_custom_grains:
  stage: test
  before_script:
    - zypper -qn in --no-recommends python3 python3-PyYAML
  script: bin/test_custom_grains.py
  tags:
    - docker

test_show_highstate_against_upstream_formulas:
  stage: test
  before_script:
    - bin/prepare_test_show_highstate_env.sh -s
    - bin/get_formulas.py -c -d /srv/formula -s
  script: bin/test_show_highstate.sh
  allow_failure: true
  tags:
    - docker

test_show_highstate_against_forked_formulas:
  stage: test
  variables:
    # TODO: get rid of GIT_SSL_NO_VERIFY as soon as we switch to letsencrypt wildcard certs
    GIT_SSL_NO_VERIFY: 'true'
  before_script:
    - bin/prepare_test_show_highstate_env.sh -s
    - bin/get_formulas.py -c -d /srv/formula -s --clone-from 'https://gitlab.infra.opensuse.org/saltstack-formulas' --clone-branch production
  script: bin/test_show_highstate.sh
  tags:
    - docker

deploy_job:
  stage: deploy
  script: sudo salt-call event.fire_master update salt/fileserver/gitfs/update
  only:
    - production
  tags:
    - shell
